=== Pisdrul/MarvelSnapSim/matchlogs/schema/schema-game.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GameStats",
  "type": "object",
  "required": ["game_id", "winner"],
  "properties": {
    "game_id": {
      "type": "string",
      "description": "Unique game identifier"
    },
    "start_time": {
      "type": "string",
      "format": "date-time",
      "description": "Start date and time of the match"
    },
    "end_time": {
      "type": "string",
      "format": "date-time",
      "description": "End date and time of the match"
    },
    "winner": {
      "type": "string",
      "enum": ["player1", "player2", "Tie"],
      "description": "Winner of the match"
    }
  }
}

=== Pisdrul/MarvelSnapSim/matchlogs/game-data.json
[
  {
    "game_id": "qW4pFw17AG",
    "winner": "player2",
    "start_time": "2025-05-12T09:56:25.577893Z",
    "end_time": "2025-05-12T09:58:50.197646Z"
  },
  {
    "game_id": "WooO4odINz",
    "winner": "player1",
    "start_time": "2025-05-12T10:25:29.939526Z",
    "end_time": "2025-05-12T10:27:24.160269Z"
  }
]
